### ISSUE TITLE
Auth0 v2.36.2

### ISSUE THREAD

**Issue by rynecheow** [auth0-extensions/canirequire#289] opened 2021-10-01 06:09 UTC
### Package info

Package Name: auth0

Package Version: v2.36.2

NPM Url: https://www.npmjs.com/package/auth0

### Reason for Request

Update package version

**Comment by turcottedanny** [comment] 2021-10-05 16:50
Duplicate of https://github.com/auth0-extensions/canirequire/issues/284

**Closed as completed by turcottedanny** 2021-10-05 16:50 UTC
Labels: released
